# Generated by Django 4.1.7 on 2023-03-12 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'мужской'), ('F', 'женский')], default='M', max_length=1, verbose_name='Пол')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default='', max_length=60, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'преподаватель',
                'verbose_name_plural': 'преподаватели',
                'ordering': ['last_name', 'first_name', 'middle_name'],
                'unique_together': {('first_name', 'last_name', 'middle_name')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Кафедра')),
                ('teachers', models.ManyToManyField(blank=True, related_name='departments', to='students.teacher', verbose_name='Преподаватели')),
            ],
            options={
                'verbose_name': 'кафедра',
                'verbose_name_plural': 'кафедры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'мужской'), ('F', 'женский')], default='M', max_length=1, verbose_name='Пол')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default='', max_length=60, verbose_name='Отчество')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='students.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'студент',
                'verbose_name_plural': 'студенты',
                'ordering': ['last_name', 'first_name', 'middle_name'],
                'unique_together': {('first_name', 'last_name', 'middle_name')},
            },
        ),
    ]
