# Generated by Django 4.1.7 on 2023-03-11 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_department_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='departments', to='students.teacher', verbose_name='Преподаватели'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='students.department', verbose_name='Кафедра'),
        ),
    ]
